# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EnerOrdia.EnerScientia
PackageVersion: 0.1.1
InstallerType: nullsoft
Scope: user
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ShuiJijun/EnerScientia/releases/download/v0.1.1/EnerScientia-0.1.1-win-x64.exe
    InstallerSha256: 21AD8FA6C963E993EB4129FB341A6A7FB00AED6BB88978D18018EFBC5E482F89
    AppsAndFeaturesEntries:
      - DisplayName: 能科智研｜EnerScientia 0.1.1
        Publisher: EnerScientia
ManifestType: installer
ManifestVersion: 1.12.0
